// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payments.Data;

#nullable disable

namespace Payments.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20230513195353_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payments.Domains.Payment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = "ef9032fc-d106-412f-9b7a-09b902db7dfz",
                            Amount = 25.80m,
                            Type = 0,
                            UserId = "ef9632fc-d406-412f-9b7a-09b902db6dfa"
                        },
                        new
                        {
                            Id = "ef9032fc-e106-412f-9b7a-0zb9x2db7df6",
                            Amount = 125.80m,
                            Type = 1,
                            UserId = "ef9632fc-d406-412f-9b7a-09b902db6dfa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
