// <auto-generated />
using System;
using Egabinet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230514195736_addColumnToTimesheet")]
    partial class addColumnToTimesheet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Domain.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = "3e01671b-18fc-4f8c-bfd8-fa12666a99b6",
                            Adress = " Kolorowa 5",
                            Name = "Adam",
                            PermissionNumber = " 569853",
                            SpecializationId = "6a3d526e-1fb6-4de7-bde5-e0754fc58aec",
                            Surname = "Kowalski",
                            UserId = "ef9632fc-d406-412f-9b7a-09b902db6dfa"
                        },
                        new
                        {
                            Id = "1769f6fc-fb40-44ed-bb10-70c0c13a97e3",
                            Adress = " Zielona 5",
                            Name = "Zofia",
                            PermissionNumber = " 560053",
                            SpecializationId = "4e8effeb-0a99-4038-9420-0c543a3a28ac",
                            Surname = "Kowalski",
                            UserId = "785a5776-fbba-4021-a263-4b9daade6ac8"
                        },
                        new
                        {
                            Id = "ba61c248-a31d-4c10-9e7c-9d8d32defeea",
                            Adress = " Adama Mickiewicza 8",
                            Name = "Todor",
                            PermissionNumber = " 160053",
                            SpecializationId = "e86959d5-6eed-45f7-b5cb-6b8f68a4d085",
                            Surname = " Nowaki",
                            UserId = "452db704-3650-457a-a7da-ca545a521776"
                        },
                        new
                        {
                            Id = "519e3b1c-8357-470d-9643-9be49bd669a3",
                            Adress = " Obozowa 8",
                            Name = "Grzegorz",
                            PermissionNumber = " 560053",
                            SpecializationId = "690e47d4-996b-43b7-a23b-d9693cf5962c",
                            Surname = "Lem",
                            UserId = "7fe50ba2-def6-4ac0-8b3e-87d3b4ce693f"
                        });
                });

            modelBuilder.Entity("Core.Domain.Nurse", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Nurse");

                    b.HasData(
                        new
                        {
                            Id = "9ae453af-8db3-440c-b8d0-1c55299ce188",
                            Address = " Różana 5",
                            Name = "AZofia",
                            PermissionNumber = " 509853",
                            Surname = "Stanecka",
                            UserId = "00221f79-bc71-4186-9e5d-bfd57a80a43f"
                        },
                        new
                        {
                            Id = "e40f8b49-f885-48c0-bb64-21c0d0813e88",
                            Address = " Topografów 5",
                            Name = "Hanna",
                            PermissionNumber = " 510053",
                            Surname = " Oklejka",
                            UserId = "32923230-6c8c-4510-b73e-d9bcf2484879"
                        },
                        new
                        {
                            Id = "68041977-3f99-4e4f-ac71-0b03a3606750",
                            Address = " os. Kolorowe 8",
                            Name = "Anna ",
                            PermissionNumber = " 169053",
                            Surname = " Austen",
                            UserId = "ed216c2a-3e1c-486f-b8ca-5f13bd8baee8"
                        },
                        new
                        {
                            Id = "965e09d6-0ed5-4e7a-8950-e252b1ae5380",
                            Address = " Obozowa 14",
                            Name = "Glżbieta Lem",
                            PermissionNumber = " 567053",
                            Surname = " Lockman",
                            UserId = "c2ebef8b-eee6-4328-ba4d-f01a04fe4f83"
                        });
                });

            modelBuilder.Entity("Core.Domain.Patient", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Pesel")
                        .HasColumnType("bigint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = "9262b74c-f7b4-47ba-8fcf-087241096f34",
                            Address = " Magnoliowa 5",
                            Name = "Adam",
                            Pesel = 85011259884L,
                            Surname = "Nowak",
                            UserId = "66126f74-f32b-435d-9e24-b3ed8b3d6011"
                        },
                        new
                        {
                            Id = "23159457-b301-4839-932a-3fd939f8b6c4",
                            Address = " Ostoja 5",
                            Name = "Zofia",
                            Pesel = 78020607221L,
                            Surname = "Stanecka",
                            UserId = "26dfb75e-5f31-4a54-9844-f019998a61d1"
                        },
                        new
                        {
                            Id = "9de0d585-60a6-445c-910c-e26ccaf46274",
                            Address = " Żeromskiego 4",
                            Name = "Austen",
                            Pesel = 95011259884L,
                            Surname = "Nowaki",
                            UserId = "64791af4-436d-4419-b3e1-14641bdb2493"
                        },
                        new
                        {
                            Id = "816c62f5-2b08-4042-8008-07a46b920921",
                            Address = " Obozowa 15",
                            Name = "Grzegorz",
                            Pesel = 65011259884L,
                            Surname = "Fus",
                            UserId = "cef7f7aa-d198-4373-b441-926d8e52dbb1"
                        });
                });

            modelBuilder.Entity("Core.Domain.Room", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = "d36af7ac-73cb-459e-847f-0abea3581814",
                            Number = 1L
                        },
                        new
                        {
                            Id = "4b4e2a8f-ab04-40ab-827d-3c7789208e4c",
                            Number = 2L
                        },
                        new
                        {
                            Id = "c5f12060-322b-42be-bba6-689e2e0c5721",
                            Number = 3L
                        },
                        new
                        {
                            Id = "525e8058-b3a1-4a9f-83e5-355848d1e6c5",
                            Number = 4L
                        });
                });

            modelBuilder.Entity("Core.Domain.Specialization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = "6a3d526e-1fb6-4de7-bde5-e0754fc58aec",
                            Value = "Lekarz rodzinny"
                        },
                        new
                        {
                            Id = "4e8effeb-0a99-4038-9420-0c543a3a28ac",
                            Value = "Endokrynolog"
                        },
                        new
                        {
                            Id = "e86959d5-6eed-45f7-b5cb-6b8f68a4d085",
                            Value = "Laryngolog"
                        },
                        new
                        {
                            Id = "690e47d4-996b-43b7-a23b-d9693cf5962c",
                            Value = "Stomatolog"
                        });
                });

            modelBuilder.Entity("Core.Domain.TimeSheet", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("TimeSheet");

                    b.HasData(
                        new
                        {
                            Id = "06223eb9-588c-4b2d-a0ab-c3c5ad65ae78",
                            Amount = 25m,
                            Data = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "3e01671b-18fc-4f8c-bfd8-fa12666a99b6",
                            PatientId = "9262b74c-f7b4-47ba-8fcf-087241096f34",
                            RoomId = "d36af7ac-73cb-459e-847f-0abea3581814"
                        },
                        new
                        {
                            Id = "56932a73-5813-4215-bc39-686b11a12afc",
                            Amount = 25m,
                            Data = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "1769f6fc-fb40-44ed-bb10-70c0c13a97e3",
                            PatientId = "23159457-b301-4839-932a-3fd939f8b6c4",
                            RoomId = "4b4e2a8f-ab04-40ab-827d-3c7789208e4c"
                        },
                        new
                        {
                            Id = "64060098-a52b-4e91-b5b6-63d292cea083",
                            Amount = 25m,
                            Data = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "ba61c248-a31d-4c10-9e7c-9d8d32defeea",
                            PatientId = "9de0d585-60a6-445c-910c-e26ccaf46274",
                            RoomId = "c5f12060-322b-42be-bba6-689e2e0c5721"
                        },
                        new
                        {
                            Id = "7fd77adc-02e5-444e-9b7e-feb2113ac22f",
                            Amount = 25m,
                            Data = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "519e3b1c-8357-470d-9643-9be49bd669a3",
                            PatientId = "816c62f5-2b08-4042-8008-07a46b920921",
                            RoomId = "525e8058-b3a1-4a9f-83e5-355848d1e6c5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "72f2ff00-761f-4727-b07c-5381992b5e0a",
                            ConcurrencyStamp = "50bff2c8-0cdd-4607-b993-63f43578192d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "c1eeb9bd-5412-495a-8abf-a4157f1b546d",
                            ConcurrencyStamp = "671dfeec-bbdf-4c82-9045-988a94174807",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "04d94d89-fe74-43ba-b052-90d5f3dea95f",
                            ConcurrencyStamp = "211aa09d-41e4-44a3-a797-87019e245d5e",
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "66126f74-f32b-435d-9e24-b3ed8b3d6011",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c24b91ca-f6c2-4ad0-b22b-f0c8f5fdbff2",
                            Email = "user1@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@OP.PL",
                            NormalizedUserName = "USER1@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEDco95GocJKJQnWtl6uxaD/VPVw5TfQnagtJL5Zb36homrX5SJKgp2wNcpNNy1SG1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ab370c5-6890-4443-843d-06042bb72373",
                            TwoFactorEnabled = false,
                            UserName = "user1@op.pl"
                        },
                        new
                        {
                            Id = "26dfb75e-5f31-4a54-9844-f019998a61d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acf857ce-42bd-4e7f-bcec-5ecdd14d54da",
                            Email = "user2@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@OP.PL",
                            NormalizedUserName = "USER2@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ+ulWBvBCeZZ+3aC9IikY2s5eW4nE3S7VIYj2HvUrkXq4+LB3kPfeRzoBGcuQ03qg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b22fff2-f4c9-4b99-b0ce-b41c57af1af0",
                            TwoFactorEnabled = false,
                            UserName = "user2@op.pl"
                        },
                        new
                        {
                            Id = "64791af4-436d-4419-b3e1-14641bdb2493",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6362a5f-eaa2-4b5d-95d8-3c43c0d95b8a",
                            Email = "user3@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@OP.PL",
                            NormalizedUserName = "USER3@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEBhezcipmSw53mtp74QjvRooh+WzXBXtKzCuklZF9TASPdkYasZzbnoyewCwkPDEGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "81c69545-d2c9-4376-9caf-e3e3fbb1e2fc",
                            TwoFactorEnabled = false,
                            UserName = "user3@op.pl"
                        },
                        new
                        {
                            Id = "cef7f7aa-d198-4373-b441-926d8e52dbb1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14ba9cf0-709f-45f7-8f50-1f7b07b71a8f",
                            Email = "user4@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@OP.PL",
                            NormalizedUserName = "USER4@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEPmQL5zeQ7cjZpIorL2/qXQ9x5Jjn/l/ItLd5FtbqpPiXNdTIZJxd2IOLQ7FrVXFeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3be959ed-db65-4f62-a190-15ab0550a33e",
                            TwoFactorEnabled = false,
                            UserName = "user4@op.pl"
                        },
                        new
                        {
                            Id = "00221f79-bc71-4186-9e5d-bfd57a80a43f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2818c3fc-d718-442f-8dfd-2824f6fd1f57",
                            Email = "user5@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@OP.PL",
                            NormalizedUserName = "USER5@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEGiFAgQCWFnJezeZl8QQTQytkI6KXQYfV87D0SpUe39TOHzFYOA/pXVXCoJx46llwQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4eb2233-7848-4eaa-8cd3-7b614d6d36bd",
                            TwoFactorEnabled = false,
                            UserName = "user5@op.pl"
                        },
                        new
                        {
                            Id = "32923230-6c8c-4510-b73e-d9bcf2484879",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7a46a5b-7118-4867-816b-0ba7f5e8ba4f",
                            Email = "user6@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@OP.PL",
                            NormalizedUserName = "USER6@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEGRPSXvbz+UAD0MgPwrOBb2CXrA9h31f4+VjPxgmd6kv5wFFyN6P6JA4A1K1Q2AxGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab8c7785-a340-4c4e-826c-7af6c958f50b",
                            TwoFactorEnabled = false,
                            UserName = "user6@op.pl"
                        },
                        new
                        {
                            Id = "ed216c2a-3e1c-486f-b8ca-5f13bd8baee8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9d37c51b-6860-4c92-bfe6-97b3628d1392",
                            Email = "user7@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@OP.PL",
                            NormalizedUserName = "USER7@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEIfp77CEIaJP+yja9cF8X53mFhoZdcuio2O+YdoqMMUpvy+4GN5jbgGc9/cJy0yWpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07508eb4-84bc-4dba-8a57-819226744d28",
                            TwoFactorEnabled = false,
                            UserName = "user7@op.pl"
                        },
                        new
                        {
                            Id = "c2ebef8b-eee6-4328-ba4d-f01a04fe4f83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8bc3bf91-6b1e-45e2-9831-a0b7b2877487",
                            Email = "user8@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@OP.PL",
                            NormalizedUserName = "USER8@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAENe+gRNxRjPRV6RO8lcb7PHAw5z5gnynBMB7Zd0LJdlmD/VRcGtIqvhwJiaOXAeEQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c47b8c9d-163c-44aa-bdcc-6a40e16aff5f",
                            TwoFactorEnabled = false,
                            UserName = "user8@op.pl"
                        },
                        new
                        {
                            Id = "ef9632fc-d406-412f-9b7a-09b902db6dfa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f3c63d0e-9375-4480-99e6-95a9f6ef4f13",
                            Email = "user9@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@OP.PL",
                            NormalizedUserName = "USER9@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFd1fmMwnkVwpe4GizokyEyJEmCC8wZTshJcwmHe2id2IM0BKn0vUsMJFLtIhG8pbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c2b0ecbd-a7ea-4a7d-b3ff-184c5e5d5ec7",
                            TwoFactorEnabled = false,
                            UserName = "user9@op.pl"
                        },
                        new
                        {
                            Id = "785a5776-fbba-4021-a263-4b9daade6ac8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eadcb9e5-fe90-42cf-b4da-2267db55dfcb",
                            Email = "user10@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER10@OP.PL",
                            NormalizedUserName = "USER10@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEH7PwKd8x0sFfTbFWVzlL0V9XaAmFVOp3VRbb5DVZXI66o3W6xSFtW34TK/ld4JNaw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4c89a0f-92cc-47b5-8df7-8a6ff5ba7450",
                            TwoFactorEnabled = false,
                            UserName = "user10@op.pl"
                        },
                        new
                        {
                            Id = "452db704-3650-457a-a7da-ca545a521776",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea25b1f7-d06e-415b-8294-1be5ec0c9f52",
                            Email = "user11@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER11@OP.PL",
                            NormalizedUserName = "USER11@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEGsKV6YM2gp0qBILTiKurl68wG/RwH1x+gI2AnoMS6GuIQ8IzJrQlThkTiUEKoosLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "86855b48-27f3-4dda-b445-d5334f94e016",
                            TwoFactorEnabled = false,
                            UserName = "user11@op.pl"
                        },
                        new
                        {
                            Id = "7fe50ba2-def6-4ac0-8b3e-87d3b4ce693f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b269c10-cdfa-42f2-a312-c8d72b5b2e58",
                            Email = "user12@op.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER12@OP.PL",
                            NormalizedUserName = "USER12@OP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEA6MWEGm+kwFwFsN9D4gKzAUMPOt+TXMW+bsuWThVyGvNMwyfKeTrG/tsALnsDP+7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9278726e-bad2-4340-80af-30725769a8cb",
                            TwoFactorEnabled = false,
                            UserName = "user12@op.pl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "66126f74-f32b-435d-9e24-b3ed8b3d6011",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "26dfb75e-5f31-4a54-9844-f019998a61d1",
                            RoleId = "c1eeb9bd-5412-495a-8abf-a4157f1b546d"
                        },
                        new
                        {
                            UserId = "64791af4-436d-4419-b3e1-14641bdb2493",
                            RoleId = "c1eeb9bd-5412-495a-8abf-a4157f1b546d"
                        },
                        new
                        {
                            UserId = "cef7f7aa-d198-4373-b441-926d8e52dbb1",
                            RoleId = "c1eeb9bd-5412-495a-8abf-a4157f1b546d"
                        },
                        new
                        {
                            UserId = "00221f79-bc71-4186-9e5d-bfd57a80a43f",
                            RoleId = "72f2ff00-761f-4727-b07c-5381992b5e0a"
                        },
                        new
                        {
                            UserId = "32923230-6c8c-4510-b73e-d9bcf2484879",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "ed216c2a-3e1c-486f-b8ca-5f13bd8baee8",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "c2ebef8b-eee6-4328-ba4d-f01a04fe4f83",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "ef9632fc-d406-412f-9b7a-09b902db6dfa",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "785a5776-fbba-4021-a263-4b9daade6ac8",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "452db704-3650-457a-a7da-ca545a521776",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        },
                        new
                        {
                            UserId = "7fe50ba2-def6-4ac0-8b3e-87d3b4ce693f",
                            RoleId = "04d94d89-fe74-43ba-b052-90d5f3dea95f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Doctor", b =>
                {
                    b.HasOne("Core.Domain.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Nurse", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Patient", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.TimeSheet", b =>
                {
                    b.HasOne("Core.Domain.Doctor", "Doctor")
                        .WithMany("TimeSheet")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Patient", "Patient")
                        .WithMany("TimeSheet")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Room", "Room")
                        .WithMany("TimeSheet")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Doctor", b =>
                {
                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("Core.Domain.Patient", b =>
                {
                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("Core.Domain.Room", b =>
                {
                    b.Navigation("TimeSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
